# Generated by Django 3.0.6 on 2020-09-06 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес')),
            ],
            options={
                'verbose_name_plural': 'Кинотеатры',
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('info', models.TextField(max_length=2000, verbose_name='Описание')),
                ('afisha_picture', models.ImageField(upload_to='images/', verbose_name='Обложка фильма')),
                ('afisha_url', models.CharField(default='https://www.google.com/', max_length=500)),
                ('age_allowed', models.PositiveSmallIntegerField(default=0, verbose_name='Возрастное ограничение')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='Продолжительность')),
                ('mark_kp', models.FloatField(default=0.0, verbose_name='Оценка кинопоиска')),
            ],
            options={
                'verbose_name_plural': 'Фильмы',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=25, verbose_name='Телефон')),
                ('cinema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='films.Cinema', verbose_name='Кинотеатр')),
            ],
            options={
                'verbose_name_plural': 'Телефоны',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата сеанса')),
                ('time', models.CharField(max_length=10, verbose_name='Время')),
                ('external_id', models.CharField(default=0, max_length=100, verbose_name='ID внешнее')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Цена')),
                ('session_format', models.CharField(default='2D', max_length=15, verbose_name='Формат сеанса')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='films.Cinema', verbose_name='Кинотеатр')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cinemas', to='films.Film', verbose_name='Фильм')),
            ],
            options={
                'verbose_name_plural': 'Сеансы',
                'unique_together': {('external_id', 'cinema')},
            },
        ),
    ]
