# Generated by Django 3.0.6 on 2020-09-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='cinema_icon',
            field=models.ImageField(default='images/Cinema_label.jpg', upload_to='images/', verbose_name='Обложка фильма'),
        ),
    ]
