# Generated by Django 3.0.6 on 2020-09-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_cinema_cinema_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='karo_id',
            field=models.PositiveIntegerField(default=0, verbose_name='ID кинотеатров КАРО'),
        ),
        migrations.AddField(
            model_name='film',
            name='rambler_id',
            field=models.PositiveIntegerField(default=0, verbose_name='ID кинотеатров Рамблера'),
        ),
    ]
