# Generated by Django 3.0.6 on 2020-09-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_auto_20200913_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='info',
            field=models.TextField(max_length=2000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='slug',
            field=models.CharField(max_length=50, null=True, verbose_name='Название транслитом'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='url',
            field=models.CharField(max_length=100, null=True, verbose_name='URL сайта'),
        ),
    ]
