FROM node

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install app dependencies
RUN apt-get update \
    && apt-get install netcat -y && apt-get install git

ADD . /usr/src/app/
RUN echo nameserver 8.8.8.8 > /etc/resolv.conf
RUN npm install

RUN npm audit fix

# Build app
RUN npm run build

ENV HOST 0.0.0.0
EXPOSE 3000

# start command
CMD [ "npm", "start" ]